name: Build and Deploy

on:
    push:
        branches:
            - main # Trigger on push to main branch
    workflow_dispatch: # Allow manual trigger from GitHub Actions tab

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: write # Required to push to the repository

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch all history for all branches

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build

            - name: Deploy build
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GH_TOKEN }}
                publish_dir: dist
                publish_branch: build-deploy